#!/bin/bash

echo "🚀 Superset Dashboard Setup Guide"
echo "================================="
echo ""
echo "✅ Trino database connection has been configured!"
echo "   Connection String: trino://admin@trino:8080/iceberg"
echo "✅ Sales data is available: $(docker exec trino trino --execute "SELECT COUNT(*) FROM iceberg.demo.sales;" 2>/dev/null) records"
echo "✅ Products data is available: $(docker exec trino trino --execute "SELECT COUNT(*) FROM iceberg.demo.products;" 2>/dev/null) records"
echo ""
echo "🌐 Access Superset at: http://localhost:8088"
echo "👤 Login credentials: admin / admin"
echo ""
echo "📊 To create the Sales Dashboard:"
echo "1. Open http://localhost:8088 in your browser"
echo "2. Login with admin/admin"
echo "3. Go to SQL Lab → SQL Editor"
echo "4. Select 'Trino Iceberg' database"
echo "5. Test with this query:"
echo ""
echo "   SELECT product_id, COUNT(*) as sales_count"
echo "   FROM demo.sales"
echo "   GROUP BY product_id"
echo "   ORDER BY sales_count DESC;"
echo ""
echo "6. To create charts:"
echo "   - Go to Charts → + (Create new chart)"
echo "   - Select 'Trino Iceberg' database"
echo "   - Select 'demo.sales' table"
echo "   - Choose chart type (Pie Chart, Bar Chart, etc.)"
echo ""
echo "7. To create dashboard:"
echo "   - Go to Dashboards → + (Create new dashboard)"
echo "   - Add the charts you created"
echo ""
echo "🔍 Sample queries for analysis:"
echo ""
echo "-- Sales count by product:"
echo "SELECT p.name, COUNT(s.id) as sales_count"
echo "FROM demo.sales s"
echo "JOIN demo.products p ON s.product_id = p.id"
echo "GROUP BY p.name"
echo "ORDER BY sales_count DESC;"
echo ""
echo "-- Total revenue by product:"
echo "SELECT p.name, SUM(s.price * s.qty) as total_revenue"
echo "FROM demo.sales s"
echo "JOIN demo.products p ON s.product_id = p.id"
echo "GROUP BY p.name"
echo "ORDER BY total_revenue DESC;"
echo ""
echo "-- Sales over time (daily):"
echo "SELECT DATE(sale_ts) as sale_date, COUNT(*) as daily_sales"
echo "FROM demo.sales"
echo "GROUP BY DATE(sale_ts)"
echo "ORDER BY sale_date;"
echo ""

# Test if Superset is accessible
if curl -s -o /dev/null -w "%{http_code}" http://localhost:8088 | grep -q "302"; then
    echo "✅ Superset is running and accessible"
else
    echo "❌ Superset may not be ready yet, please wait a moment"
fi

echo ""
echo "🎯 Quick Start: Open http://localhost:8088 now!"